-- Alimentos genéricos, orientativos, sin precio.
-- Nutrición: Open Food Facts, por 100 g. Foto: Wikimedia Commons. Sin precio.
-- category incluye las etiquetas del alimento y la etiqueta general.
BEGIN;
CREATE TABLE IF NOT EXISTS GeneralFood (
  name TEXT PRIMARY KEY,
  category TEXT NOT NULL,
  kcal REAL NOT NULL,
  protein REAL NOT NULL,
  carbs REAL NOT NULL,
  fat REAL NOT NULL,
  imageUrl TEXT NOT NULL
);
DELETE FROM GeneralFood;
INSERT INTO GeneralFood (name, category, kcal, protein, carbs, fat, imageUrl) VALUES ('Pechuga de pollo', 'pollo, carne, general', 142.86, 21.43, 0.89, 6.25, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b8/Raw_chicken_slices.jpg/330px-Raw_chicken_slices.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail');
INSERT INTO GeneralFood (name, category, kcal, protein, carbs, fat, imageUrl) VALUES ('Muslo de pollo', 'pollo, carne, general', 172.0, 18.0, 0.5, 11.0, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4e/Raw_chicken_thighs.jpg/330px-Raw_chicken_thighs.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail');
INSERT INTO GeneralFood (name, category, kcal, protein, carbs, fat, imageUrl) VALUES ('Pechuga de pavo', 'pavo, carne, general', 111.11, 13.89, 0.0, 2.78, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f0/Carraca_lila_%28Coracias_caudata%29%2C_parque_nacional_Kruger%2C_Sud%C3%A1frica%2C_2018-07-26%2C_DD_17.jpg/330px-Carraca_lila_%28Coracias_caudata%29%2C_parque_nacional_Kruger%2C_Sud%C3%A1frica%2C_2018-07-26%2C_DD_17.jpg?utm_source=commons.wiki');
INSERT INTO GeneralFood (name, category, kcal, protein, carbs, fat, imageUrl) VALUES ('Ternera magra', 'ternera, carne, general', 145.0, 23.0, 0.5, 5.7, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fd/Steak_Tartare_in_Dresden.jpg/330px-Steak_Tartare_in_Dresden.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail');
INSERT INTO GeneralFood (name, category, kcal, protein, carbs, fat, imageUrl) VALUES ('Lomo de cerdo', 'cerdo, carne, general', 154.0, 21.8, 0.5, 7.2, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/2/26/Milano%27s_Caf%C3%A9_pork_loin_and_veg_Russell_Street_Stroud_Gloucestershire_England_04.jpg/330px-Milano%27s_Caf%C3%A9_pork_loin_and_veg_Russell_Street_Stroud_Gloucestershire_England_04.jpg?utm_source=commons.wikimedia.org&utm_campaign=imagein');
INSERT INTO GeneralFood (name, category, kcal, protein, carbs, fat, imageUrl) VALUES ('Huevo', 'huevos, general', 150.0, 12.5, 0.0, 11.1, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fb/Chicken_Egg_without_Eggshell_5859.jpg/330px-Chicken_Egg_without_Eggshell_5859.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail');
INSERT INTO GeneralFood (name, category, kcal, protein, carbs, fat, imageUrl) VALUES ('Clara de huevo', 'huevos, general', 54.35, 10.87, 2.17, 0.0, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fb/Chicken_Egg_without_Eggshell_5859.jpg/330px-Chicken_Egg_without_Eggshell_5859.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail');
INSERT INTO GeneralFood (name, category, kcal, protein, carbs, fat, imageUrl) VALUES ('Salmón', 'pescado, general', 192.0, 17.8, 1.0, 12.9, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/4/48/Raw_salmon_2.jpg/330px-Raw_salmon_2.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail');
INSERT INTO GeneralFood (name, category, kcal, protein, carbs, fat, imageUrl) VALUES ('Merluza', 'pescado, general', 93.0, 15.0, 0.0, 9.0, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8c/American_fishes_%28Page_%28489%29%2C_Figure-_Lake_White_Fish%29_BHL6310342.jpg/330px-American_fishes_%28Page_%28489%29%2C_Figure-_Lake_White_Fish%29_BHL6310342.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail');
INSERT INTO GeneralFood (name, category, kcal, protein, carbs, fat, imageUrl) VALUES ('Atún', 'pescado, general', 143.33, 20.0, 0.0, 6.67, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8b/Tuna_tartar.jpg/330px-Tuna_tartar.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail');
INSERT INTO GeneralFood (name, category, kcal, protein, carbs, fat, imageUrl) VALUES ('Gambas', 'pescado, general', 102.0, 22.8, 0.5, 1.0, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c2/Raw_shrimp.jpg/330px-Raw_shrimp.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail');
INSERT INTO GeneralFood (name, category, kcal, protein, carbs, fat, imageUrl) VALUES ('Bacalao', 'pescado, general', 68.7, 16.3, 0.5, 0.17, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e7/Cape_Cod_Hospital_in_Hyannis.jpg/330px-Cape_Cod_Hospital_in_Hyannis.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail');
INSERT INTO GeneralFood (name, category, kcal, protein, carbs, fat, imageUrl) VALUES ('Leche entera', 'lacteos, general', 64.0, 3.2, 4.6, 3.6, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f8/2025.04.10_Milk_Glass_Sugar_Bowl_and_Antique_Glass_Creamer.jpg/330px-2025.04.10_Milk_Glass_Sugar_Bowl_and_Antique_Glass_Creamer.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail');
INSERT INTO GeneralFood (name, category, kcal, protein, carbs, fat, imageUrl) VALUES ('Leche desnatada', 'lacteos, general', 35.0, 3.1, 4.8, 0.3, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bf/Skim_milk_poured_into_cereal_bowl.jpg/330px-Skim_milk_poured_into_cereal_bowl.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail');
INSERT INTO GeneralFood (name, category, kcal, protein, carbs, fat, imageUrl) VALUES ('Yogur natural', 'lacteos, general', 66.0, 5.5, 4.95, 2.7, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b8/Joghurt.jpg/330px-Joghurt.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail');
INSERT INTO GeneralFood (name, category, kcal, protein, carbs, fat, imageUrl) VALUES ('Queso fresco', 'lacteos, general', 250.0, 25.0, 3.57, 17.86, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a1/Cottage_Cheese.jpg/330px-Cottage_Cheese.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail');
INSERT INTO GeneralFood (name, category, kcal, protein, carbs, fat, imageUrl) VALUES ('Arroz blanco', 'arroz, cereal, general', 168.3, 3.1, 38.3, 1.0, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e6/Cooked_green_rice_and_white_rice.jpg/330px-Cooked_green_rice_and_white_rice.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail');
INSERT INTO GeneralFood (name, category, kcal, protein, carbs, fat, imageUrl) VALUES ('Arroz integral', 'arroz, cereal, general', 172.0, 3.0, 39.0, 0.0, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9c/Par_cooked_brown_rice_-_stonesoup_cropped.jpg/330px-Par_cooked_brown_rice_-_stonesoup_cropped.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail');
INSERT INTO GeneralFood (name, category, kcal, protein, carbs, fat, imageUrl) VALUES ('Pasta', 'pasta, cereal, general', 155.0, 8.82, 17.93, 4.97, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/b/be/Sour_pasta_with_tomatoes_and_spinach.jpg/330px-Sour_pasta_with_tomatoes_and_spinach.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail');
INSERT INTO GeneralFood (name, category, kcal, protein, carbs, fat, imageUrl) VALUES ('Pan', 'pan, cereal, general', 266.0, 9.7, 45.0, 4.6, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/33/Fresh_made_bread_05.jpg/330px-Fresh_made_bread_05.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail');
INSERT INTO GeneralFood (name, category, kcal, protein, carbs, fat, imageUrl) VALUES ('Avena', 'cereal, general', 382.0, 14.0, 60.0, 7.2, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/9/97/Rolled_oats.jpg/330px-Rolled_oats.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail');
INSERT INTO GeneralFood (name, category, kcal, protein, carbs, fat, imageUrl) VALUES ('Quinoa', 'cereal, general', 141.0, 4.3, 22.7, 2.7, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b9/Liat_Portal_for_Foodie_Disorder_-_Quinoa%2C_Schnitzel_and_Israeli_Salad.jpg/330px-Liat_Portal_for_Foodie_Disorder_-_Quinoa%2C_Schnitzel_and_Israeli_Salad.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail');
INSERT INTO GeneralFood (name, category, kcal, protein, carbs, fat, imageUrl) VALUES ('Patata', 'verduras, general', 88.0, 2.0, 19.0, 0.0, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/4/41/Raw_sweet_potato.jpg/330px-Raw_sweet_potato.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail');
INSERT INTO GeneralFood (name, category, kcal, protein, carbs, fat, imageUrl) VALUES ('Boniato', 'verduras, general', 101.0, 1.2, 23.0, 0.3, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3f/Ipomoea_batatas_%28Sweet_Potato%29_Flower.jpg/330px-Ipomoea_batatas_%28Sweet_Potato%29_Flower.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail');
INSERT INTO GeneralFood (name, category, kcal, protein, carbs, fat, imageUrl) VALUES ('Lentejas', 'legumbres, general', 108.46, 7.0, 18.46, 0.77, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/9/93/Liat_Portal_for_Foodie_Disorder_-_Cooked_Lentils_with_Caramelized_Onions.jpg/330px-Liat_Portal_for_Foodie_Disorder_-_Cooked_Lentils_with_Caramelized_Onions.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail');
INSERT INTO GeneralFood (name, category, kcal, protein, carbs, fat, imageUrl) VALUES ('Garbanzos', 'legumbres, general', 142.31, 8.46, 21.54, 1.38, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/2/20/Chickpeas_-_The_Coconut_Island_2025-10-05.jpg/330px-Chickpeas_-_The_Coconut_Island_2025-10-05.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail');
INSERT INTO GeneralFood (name, category, kcal, protein, carbs, fat, imageUrl) VALUES ('Alubias', 'legumbres, general', 104.0, 7.2, 13.8, 0.8, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/11/Cooked_Samp_mixed_with_Black_Eye_beans.jpg/330px-Cooked_Samp_mixed_with_Black_Eye_beans.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail');
INSERT INTO GeneralFood (name, category, kcal, protein, carbs, fat, imageUrl) VALUES ('Tofu', 'proteina, general', 125.0, 12.0, 2.3, 7.5, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5b/Milk_tofu.JPG/330px-Milk_tofu.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail');
INSERT INTO GeneralFood (name, category, kcal, protein, carbs, fat, imageUrl) VALUES ('Tomate', 'verduras, general', 21.0, 0.9, 3.9, 0.2, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/88/Bright_red_tomato_and_cross_section02.jpg/330px-Bright_red_tomato_and_cross_section02.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail');
INSERT INTO GeneralFood (name, category, kcal, protein, carbs, fat, imageUrl) VALUES ('Lechuga', 'verduras, general', 19.0, 1.4, 1.6, 0.5, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6b/Romaine_lettuce.jpg/330px-Romaine_lettuce.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail');
INSERT INTO GeneralFood (name, category, kcal, protein, carbs, fat, imageUrl) VALUES ('Brócoli', 'verduras, general', 45.0, 4.5, 6.8, 0.0, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/4/40/Raw_broccoli_bunches.JPG/330px-Raw_broccoli_bunches.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail');
INSERT INTO GeneralFood (name, category, kcal, protein, carbs, fat, imageUrl) VALUES ('Zanahoria', 'verduras, general', 30.0, 0.0, 5.0, 1.0, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/32/Carrots_of_many_colors.jpg/330px-Carrots_of_many_colors.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail');
INSERT INTO GeneralFood (name, category, kcal, protein, carbs, fat, imageUrl) VALUES ('Cebolla', 'verduras, general', 40.2, 2.8, 6.73, 0.0, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a2/Mixed_onions.jpg/330px-Mixed_onions.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail');
INSERT INTO GeneralFood (name, category, kcal, protein, carbs, fat, imageUrl) VALUES ('Manzana', 'frutas, general', 52.0, 0.5, 16.0, 0.0, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/15/Red_Apple.jpg/330px-Red_Apple.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail');
INSERT INTO GeneralFood (name, category, kcal, protein, carbs, fat, imageUrl) VALUES ('Plátano', 'frutas, general', 93.0, 1.4, 21.7, 0.5, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/31/Cavendish_banana_from_Maracaibo.jpg/330px-Cavendish_banana_from_Maracaibo.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail');
INSERT INTO GeneralFood (name, category, kcal, protein, carbs, fat, imageUrl) VALUES ('Naranja', 'frutas, general', 50.85, 0.42, 12.71, 0.0, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e3/Oranges_-_whole-halved-segment.jpg/330px-Oranges_-_whole-halved-segment.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail');
INSERT INTO GeneralFood (name, category, kcal, protein, carbs, fat, imageUrl) VALUES ('Aceite de oliva', 'aceites, general', 866.67, 0.0, 0.0, 93.33, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/4/41/Olive_oil_bottle_Bertolli_Riserva_Premium.jpg/330px-Olive_oil_bottle_Bertolli_Riserva_Premium.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail');
INSERT INTO GeneralFood (name, category, kcal, protein, carbs, fat, imageUrl) VALUES ('Almendra', 'frutos secos, general', 567.0, 21.2, 9.5, 49.4, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/37/Almonds_-_in_shell%2C_shell_cracked_open%2C_shelled%2C_blanched.jpg/330px-Almonds_-_in_shell%2C_shell_cracked_open%2C_shelled%2C_blanched.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail');
INSERT INTO GeneralFood (name, category, kcal, protein, carbs, fat, imageUrl) VALUES ('Nuez', 'frutos secos, general', 673.0, 19.0, 5.3, 63.0, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1b/Juglans_regia_2009_G2.jpg/330px-Juglans_regia_2009_G2.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail');
INSERT INTO GeneralFood (name, category, kcal, protein, carbs, fat, imageUrl) VALUES ('Miel', 'dulces, general', 320.0, 0.5, 80.0, 0.5, 'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/38/Honey_Jar_icon.svg/330px-Honey_Jar_icon.svg.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail');
COMMIT;
